version: '3.4'

services:
  launchpadcodechallenge.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "40080:80"
      - "40443:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro