// <auto-generated />
using System;
using LaunchpadCodeChallenge.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaunchpadCodeChallenge.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("LaunchpadCodeChallenge.Models.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a5052a2-f0d2-4870-91e1-2d47dcce91a0"),
                            Address = "5th floor",
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = new Guid("32765d3e-4e43-41a3-8177-4409cb508b7a"),
                            Address = "7th floor",
                            Name = "Administration"
                        });
                });

            modelBuilder.Entity("LaunchpadCodeChallenge.Models.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5845a58-f668-4459-9d4b-70ddc5197fec"),
                            Address = "123 My Street",
                            DepartmentId = new Guid("7a5052a2-f0d2-4870-91e1-2d47dcce91a0"),
                            FirstName = "Vivi",
                            JobTitle = "Software Developer",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = new Guid("dc7814a6-5d0c-45f7-8096-ff8bb90d69e3"),
                            Address = "345 23rd St, NE",
                            DepartmentId = new Guid("7a5052a2-f0d2-4870-91e1-2d47dcce91a0"),
                            FirstName = "Jack",
                            JobTitle = "Software Developer",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("42374644-1216-4411-8645-a7732270f165"),
                            Address = "19934 15 Ave, NE",
                            DepartmentId = new Guid("32765d3e-4e43-41a3-8177-4409cb508b7a"),
                            FirstName = "John",
                            JobTitle = "Receptionist",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("848866eb-c5b9-4a72-97f3-0af770123355"),
                            Address = "4532 Briar Hill Way, SW",
                            DepartmentId = new Guid("7a5052a2-f0d2-4870-91e1-2d47dcce91a0"),
                            FirstName = "Millie",
                            JobTitle = "Software Architect",
                            LastName = "Peterson"
                        });
                });

            modelBuilder.Entity("LaunchpadCodeChallenge.Models.Entities.Employee", b =>
                {
                    b.HasOne("LaunchpadCodeChallenge.Models.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("LaunchpadCodeChallenge.Models.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
